name: Java Autograding

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up JDK 11 (you can modify this to other versions if needed)
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      # Step 3: Compile the Java code
      - name: Compile Java Code
        run: |
          mkdir -p bin
          javac -d bin -cp .:libs/junit-4.12.jar src/main/java/com/yagicamp/*.java
          javac -d bin -cp .:bin:libs/junit-4.12.jar:libs/hamcrest-core-1.3.jar src/test/java/com/yagicamp/*.java

      # Step 4: Run the JUnit tests
      - name: Run JUnit Tests
        run: |
          java -cp .:bin:libs/junit-4.12.jar:libs/hamcrest-core-1.3.jar org.junit.runner.JUnitCore com.yagicamp.CalculatorTest

      # Step 5: Collect test results (optional)
      - name: Archive test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: bin/test-results
